/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (serverstate-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    serverstate.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "serverstate-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
#include "smtp_worker.h"
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Enumeration of the valid transition types
 *  Some transition types may be common to several transitions.
 */
typedef enum {
    FSM_TR_ADD_RCPT,
    FSM_TR_AWAITING_COMM_MAIL_FROM,
    FSM_TR_AWAITING_DATA_ENDDATA,
    FSM_TR_AWAITING_RCPT_DATA,
    FSM_TR_DO_QUIT,
    FSM_TR_DO_TIMEOUT,
    FSM_TR_HANDLE_GREETING,
    FSM_TR_HANDLE_UNKNOWN,
    FSM_TR_HANDLE_VRFY,
    FSM_TR_INVALID
} te_fsm_trans;
#define FSM_TRANSITION_CT  10

/**
 *  State transition handling map.  Map the state enumeration and the event
 *  enumeration to the new state and the transition enumeration code (in that
 *  order).  It is indexed by first the current state and then the event code.
 */
typedef struct fsm_transition t_fsm_transition;
struct fsm_transition {
    te_fsm_state  next_state;
    te_fsm_trans  transition;
};
static const t_fsm_transition
fsm_trans_table[ FSM_STATE_CT ][ FSM_EVENT_CT ] = {

  /* STATE 0:  FSM_ST_INIT */
  { { FSM_ST_INIT, FSM_TR_HANDLE_UNKNOWN },         /* EVT:  UNKNOWN */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  HELO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  EHLO */
    { FSM_ST_INIT, FSM_TR_HANDLE_GREETING },        /* EVT:  RSET */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_DO_QUIT },             /* EVT:  QUIT */
    { FSM_ST_INIT, FSM_TR_HANDLE_VRFY },            /* EVT:  VRFY */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  RCPT_TO */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  DATA */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_DO_TIMEOUT }           /* EVT:  TIMEOUT */
  },


  /* STATE 1:  FSM_ST_AWAITING_COMM */
  { { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_UNKNOWN }, /* EVT:  UNKNOWN */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  HELO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  EHLO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  RSET */
    { FSM_ST_AWAITING_ADDRESS, FSM_TR_AWAITING_COMM_MAIL_FROM }, /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_DO_QUIT },             /* EVT:  QUIT */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_VRFY },   /* EVT:  VRFY */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  RCPT_TO */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  DATA */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_DO_TIMEOUT }           /* EVT:  TIMEOUT */
  },


  /* STATE 2:  FSM_ST_QUITTED */
  { { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  UNKNOWN */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  HELO */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  EHLO */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  RSET */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  QUIT */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  VRFY */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  RCPT_TO */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  DATA */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_QUITTED, FSM_TR_INVALID },             /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_INVALID }              /* EVT:  TIMEOUT */
  },


  /* STATE 3:  FSM_ST_AWAITING_ADDRESS */
  { { FSM_ST_AWAITING_ADDRESS, FSM_TR_HANDLE_UNKNOWN }, /* EVT:  UNKNOWN */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  HELO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  EHLO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  RSET */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_DO_QUIT },             /* EVT:  QUIT */
    { FSM_ST_AWAITING_ADDRESS, FSM_TR_HANDLE_VRFY }, /* EVT:  VRFY */
    { FSM_ST_AWAITING_RCPT, FSM_TR_ADD_RCPT },      /* EVT:  RCPT_TO */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  DATA */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_DO_TIMEOUT }           /* EVT:  TIMEOUT */
  },


  /* STATE 4:  FSM_ST_AWAITING_RCPT */
  { { FSM_ST_AWAITING_RCPT, FSM_TR_HANDLE_UNKNOWN }, /* EVT:  UNKNOWN */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  HELO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  EHLO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  RSET */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_DO_QUIT },             /* EVT:  QUIT */
    { FSM_ST_AWAITING_RCPT, FSM_TR_HANDLE_VRFY },   /* EVT:  VRFY */
    { FSM_ST_AWAITING_RCPT, FSM_TR_ADD_RCPT },      /* EVT:  RCPT_TO */
    { FSM_ST_AWAITING_DATA, FSM_TR_AWAITING_RCPT_DATA }, /* EVT:  DATA */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_DO_TIMEOUT }           /* EVT:  TIMEOUT */
  },


  /* STATE 5:  FSM_ST_AWAITING_DATA */
  { { FSM_ST_AWAITING_DATA, FSM_TR_HANDLE_UNKNOWN }, /* EVT:  UNKNOWN */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  HELO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  EHLO */
    { FSM_ST_AWAITING_COMM, FSM_TR_HANDLE_GREETING }, /* EVT:  RSET */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MAIL_FROM */
    { FSM_ST_QUITTED, FSM_TR_DO_QUIT },             /* EVT:  QUIT */
    { FSM_ST_AWAITING_DATA, FSM_TR_HANDLE_VRFY },   /* EVT:  VRFY */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  RCPT_TO */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  DATA */
    { FSM_ST_INVALID, FSM_TR_INVALID },             /* EVT:  MESSAGE */
    { FSM_ST_AWAITING_COMM, FSM_TR_AWAITING_DATA_ENDDATA }, /* EVT:  ENDDATA */
    { FSM_ST_QUITTED, FSM_TR_DO_TIMEOUT }           /* EVT:  TIMEOUT */
  }
};


#define FsmFsmErr_off     19
#define FsmEvInvalid_off  75
#define FsmStInit_off     83


static char const zFsmStrings[235] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "awaiting_comm\0"
/*   102 */ "quitted\0"
/*   110 */ "awaiting_address\0"
/*   127 */ "awaiting_rcpt\0"
/*   141 */ "awaiting_data\0"
/*   155 */ "unknown\0"
/*   163 */ "helo\0"
/*   168 */ "ehlo\0"
/*   173 */ "rset\0"
/*   178 */ "mail_from\0"
/*   188 */ "quit\0"
/*   193 */ "vrfy\0"
/*   198 */ "rcpt_to\0"
/*   206 */ "data\0"
/*   211 */ "message\0"
/*   219 */ "enddata\0"
/*   227 */ "timeout";

static const size_t aszFsmStates[6] = {
    83,  88,  102, 110, 127, 141 };

static const size_t aszFsmEvents[13] = {
    155, 163, 168, 173, 178, 188, 193, 198, 206, 211, 219, 227, 75 };


#define FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 13) \
    ? zFsmStrings : zFsmStrings + aszFsmEvents[t])

#define FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 6) \
    ? zFsmStrings : zFsmStrings + aszFsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

//static int fsm_invalid_transition( te_fsm_state st, te_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */

// static int
// fsm_invalid_transition( te_fsm_state st, te_fsm_event evt )
// {
//     /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
//     char const * fmt = zFsmStrings + FsmFsmErr_off;
//     fprintf( stderr, fmt, st, FSM_STATE_NAME(st), evt, FSM_EVT_NAME(evt));
//     /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

//     return EXIT_FAILURE;
// }

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  FSM_ST_DONE or FSM_ST_INVALID, it resets to
 *  FSM_ST_INIT and returns FSM_ST_INIT.
 */
te_fsm_state
fsm_step(
    te_fsm_state fsm_state,
    te_fsm_event trans_evt,
    void *worker_state, void *thread_state, void *msg )
{
    te_fsm_state nxtSt;
    te_fsm_trans trans;

    if ((unsigned)fsm_state >= FSM_ST_INVALID) {
        return FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= FSM_EV_INVALID) {
        nxtSt = FSM_ST_INVALID;
        trans = FSM_TR_INVALID;
    } else
#endif /* __COVERITY__ */
    {
        const t_fsm_transition * ttbl =
            fsm_trans_table[ fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        trans = ttbl->transition;
    }


    switch (trans) {
    case FSM_TR_ADD_RCPT:
        /* START == ADD_RCPT == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_rcptto(nxtSt, tstate, cstate, match);
        }
        /* END   == ADD_RCPT == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_AWAITING_COMM_MAIL_FROM:
        /* START == AWAITING_COMM_MAIL_FROM == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_mailfrom(nxtSt, tstate, cstate, match);
        }
        /* END   == AWAITING_COMM_MAIL_FROM == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_AWAITING_DATA_ENDDATA:
        /* START == AWAITING_DATA_ENDDATA == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = {0};
            server_recv_enddata(nxtSt, tstate, cstate, match);
        }
        /* END   == AWAITING_DATA_ENDDATA == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_AWAITING_RCPT_DATA:
        /* START == AWAITING_RCPT_DATA == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_data(nxtSt, tstate, cstate, match);
        }
        /* END   == AWAITING_RCPT_DATA == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_DO_QUIT:
        /* START == DO_QUIT == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_quit(nxtSt, tstate, cstate, match);
        }
        /* END   == DO_QUIT == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_DO_TIMEOUT:
        /* START == DO_TIMEOUT == DO NOT CHANGE THIS COMMENT */
        {
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            server_timeout(nxtSt, cstate);
        }
        /* END   == DO_TIMEOUT == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_HANDLE_GREETING:
        /* START == HANDLE_GREETING == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            if (match.command == CLIENT_HELO)
            {
                server_recv_helo(nxtSt, tstate, cstate, match);
            }
            else if (match.command == CLIENT_EHLO)
            {
                server_recv_ehlo(nxtSt, tstate, cstate, match);
            }
            else if (match.command == CLIENT_RSET)
            {
                server_recv_rset(nxtSt, tstate, cstate, match);
            }
        }
        /* END   == HANDLE_GREETING == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_HANDLE_UNKNOWN:
        /* START == HANDLE_UNKNOWN == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_unknown(nxtSt, tstate, cstate, match);
        }
        /* END   == HANDLE_UNKNOWN == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_HANDLE_VRFY:
        /* START == HANDLE_VRFY == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            server_recv_vrfy(nxtSt, tstate, cstate, match);
        }
        /* END   == HANDLE_VRFY == DO NOT CHANGE THIS COMMENT */
        break;


    case FSM_TR_INVALID:
        /* START == INVALID == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            nxtSt = cstate->state;
            server_recv_error(nxtSt, tstate, cstate, match);
        }
        /* END   == INVALID == DO NOT CHANGE THIS COMMENT */
        break;


    default:
        /* START == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
        {
            smtp_worker_thread_state_t *tstate = (smtp_worker_thread_state_t*)thread_state;
            smtp_connection_state_t *cstate = (smtp_connection_state_t*)worker_state;
            command_match_t match = *(command_match_t*)msg;
            nxtSt = cstate->state;
            server_recv_unknown(nxtSt, tstate, cstate, match);
        }
        /* END   == BROKEN MACHINE == DO NOT CHANGE THIS COMMENT */
    }


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of serverstate-fsm.c */
